version: '3'
services:
    web:
        image: webdevops/php-apache-dev:8.1
        container_name: backend_not_apple
        restart: "no"
        user: root
        environment:
          - WEB_ALIAS_DOMAIN=backend.loc
          - WEB_DOCUMENT_ROOT=/app
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=4G
          - PHP_MAX_EXECUTION_TIME=18000
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
          - COMPOSER_VERSION=2
          - PHP_DEBUGGER=none # comment this parameter to enable xDebug by default
          - XDEBUG_START_WITH_REQUEST=yes
          - XDEBUG_REMOTE_HOST=host.docker.internal
          - XDEBUG_REMOTE_PORT=9000
          - XDEBUG_REMOTE_CONNECT_BACK=0
          - XDEBUG_REMOTE_AUTOSTART=1
        volumes:
          - ./:/app:cached
        ports:
          - "80:80"
          - "443:443"
          - "32823:22"

